# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FISFontingAwesome' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FISFontingAwesome

  pod 'FontAwesomeKit', '~> 2.2.0'
  pod 'CWStatusBarNotification', '~> 2.3'

  target 'FISFontingAwesomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FISFontingAwesomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
